### ISSUE TITLE
unhashable type: 'Series'

### ISSUE THREAD

**Issue by LJZYaaa** [axelalmet/flowsig#12]
Hi! I'm very interesting in your powerful tool, and trying to apply it to my own data.  But when i run the code in your tutolial :
fs.pp.construct_flows_from_cellchat(adata,
                                cellchat_output_key,
                                gem_expr_key = 'X_gem',
                                scale_gem_expr = True,
                                model_organism = 'human',
                                flowsig_network_key = 'flowsig_network',
                                flowsig_expr_key = 'X_flow')
it report that:
![image](https://github.com/user-attachments/assets/ebdb84ef-b8dd-4b6d-9df0-bfa682a211d4)

what's more, when i skip this code and try the next one , it en even report that：
![image](https://github.com/user-attachments/assets/3d362407-fd2d-4997-a748-3cf740fe0f8e)

 is the version in your tutotial not the same as it in the repositort? and how to update it? 
Looking forward to your reply, and hope anything goes well on you! ^^

**Comment by LJZYaaa** [comment]
@axelalmet

**Comment by axelalmet** [comment]
Hi,

Thanks for your question! To respond to each of your questions:

1. It looks like you're running an older version of FlowSig. Could you try updating to the latest version in the GitHub repository and running `fs.pp.construct_Flows_from_cellchat` again?

2. You're quite right, the tutorial to construct differentially flowing variables in the README.md is out of date. Apologies for this mistake! Instead of running `fs.pp.determine_informative_variables`, please run:
```
fs.pp.determine_differentially_flowing_vars(adata,
                                        condition_key = condition_key,
                                        control_key = 'CON',
                                        flowsig_expr_key = 'X_flow',
                                        flowsig_network_key = 'flowsig_network',
                                        qval_threshold = 0.05,
                                        logfc_threshold = 0.5)
```
I've updated the README.md to reflect this.

Hope these help!

**Comment by LJZYaaa** [comment]
Glad to receive your reply! I do try to update flowsig by installing it again as your tutotial, but  the version still is the 0.1.0  could you ples tell me how to update it correctly?  ^^ @axelalmet

**Comment by LJZYaaa** [comment]
Hi, i do install flowsig again, and the fs.pp.construct_flows_from_cellchat() don't report  error anymore. But when i try to run the command fs.pp.determine_differentially_flowing_vars() as your reply, it says that:
![image](https://github.com/user-attachments/assets/3606c6dc-5b98-4aab-bef0-d20e8cc4eb33)
maybe the version in your repositort is not the same as in your labs?
Looking forward to your reply, hope anything goes well on you~~ ^^

**Comment by LJZYaaa** [comment]
Another question is that  how can we visulize the result as it in your paper? :)

**Comment by yixudong** [comment]
> Hi, i do install flowsig again, and the fs.pp.construct_flows_from_cellchat() don't report error anymore. But when i try to run the command fs.pp.determine_differentially_flowing_vars() as your reply, it says that: ![image](https://private-user-images.githubusercontent.com/154489974/368482917-3606c6dc-5b98-4aab-bef0-d20e8cc4eb33.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwNTI3NjksIm5iZiI6MTcyNzA1MjQ2OSwicGF0aCI6Ii8xNTQ0ODk5NzQvMzY4NDgyOTE3LTM2MDZjNmRjLTViOTgtNGFhYi1iZWYwLWQyMGU4Y2M0ZWIzMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyM1QwMDQ3NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNTNiOWJmMTQxNzRiM2YxYmM3YjI0N2FiNWVkNTQ2YzNjNDY0ZDhhZWExMDIyM2YyZjRjOWUyNmE4N2Q0NDhiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.V5apN4TdVsppR9xsrz8uWL2h4AGzV_KFCB6Nr_Po_b8) maybe the version in your repositort is not the same as in your labs? Looking forward to your reply, hope anything goes well on you~~ ^^

Hi, [LJZYaaa](https://github.com/LJZYaaa), I'm having the same issue. 
![image](https://github.com/user-attachments/assets/4ba59464-6e85-42c2-9ff9-4940b9cda01b)
Have you solved this problem now?

**Comment by yixudong** [comment]
> Another question is that how can we visulize the result as it in your paper? :)

@axelalmet

**Comment by LJZYaaa** [comment]
Not yet :) the author has been inactive in some time :)
